---
# NodeJS repository handling and installation

  - name: Ensure apt-transport-https is installed.
    apt: name=apt-transport-https state=present
    become: yes

  #- name: Add Nodesource apt key.
  #  apt_key:
  #    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
  #    id: "68576280"
  #    state: present
  #  become: yes
  #
  #- name: Add NodeSource repositories for Node.js.
  #  apt_repository:
  #    repo: "deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
  #    state: present
  #  become: yes

  - name: Ensure Node.js is installed (The Nodesource package also contains npm)
    apt: name=nodejs state=present
    become: yes
